version: "3.8"

services:
  run-tests:
    build: .
    stdin_open: true
    tty: true
    command: sh -c "coverage run -m pytest && coverage report && coverage html"
    environment:
      DATABASE_URI: postgresql://test_user:test_password@db:5432/test_db
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db:database"
    volumes:
      - .:/app  
      - ./coverage_html:/app/tests/htmlcov 

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_password"
      PGUSER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./api/db/postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 10s
      timeout: 5s
      retries: 5
